### ISSUE TITLE
데이터베이스 스키마 설계

### ISSUE THREAD

**Issue by ryuseongryong** [codestates/Loca-Musica#14]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 목업 데이터를 넣어 데이터베이스 구현

### TODO
1. [ ] Job1 데이터베이스 세부 테이블 구현
2. [ ] Job2 목업 데이터 입력
3. [ ] Job3 서버와 연동

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
