### ISSUE TITLE
Signup HTTP 메소드 관련 구현

### ISSUE THREAD

**Issue by ryuseongryong** [codestates/Loca-Musica#15]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: /signup POST 요청에 따른 데이터베이스 갱신 구현

### TODO
1. [ ] Job1 /signup POST 요청에 따라 데이터베이스 갱신하기
2. [ ] Job2 전달받은 데이터가 충분하지 않은 경우 response 를 통해 재요청
3. [ ] Job3 전달받은 데이터가 이미 존재하는 경우 response 를 통해 재요청
4. [ ] Job4 성공했을 시 response 구현

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
