### ISSUE TITLE
소셜 로그인 구현

### ISSUE THREAD

**Issue by ryuseongryong** [codestates/Loca-Musica#19]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 네이버 소셜 로그인 구현

### TODO
1. [ ] Job1 API 문서 파악
2. [ ] Job2 소셜 로그인 기능 구현
3. [ ] Job3 카카오에서 정보 연동해 데이터베이스 추가하기

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
