### ISSUE TITLE
초기 개발 환경 구축하기

### ISSUE THREAD

**Issue by ryuseongryong** [codestates/Loca-Musica#2]
### ISSUE
- Group:  `sr`
- Type: `feature`
- Detail: 초기 개발 환경 구축하기(NPM, CRA(create-react-app) 등)

### TODO
1. [ ] Job1 사용할 모듈 및 라이브러리 정하기
2. [ ] Job2 package.json 작성하기
3. [ ] Job3 코드 컨벤션 통일하기(ESLint, Prettier 등)

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 3h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
