### ISSUE TITLE
[뮤지컬 추천 목업] 해시태그별 사용자가 선택할 수 있는 요소들 배치하기

### ISSUE THREAD

**Issue by ryuseongryong** [codestates/Loca-Musica#24]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 뮤지컬 추천 목업 구현

### TODO
1. [ ] Job1 각종 정보 표현을 위한 목업 구현
2. [ ] Job2 정보 선택 및 다중 선택 기능 구현
3. [ ] Job3 취소 및 확인 버튼 구현

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
