### ISSUE TITLE
[뮤지컬 해시태그 입력] 서버 기능 구현

### ISSUE THREAD

**Issue by ryuseongryong** [codestates/Loca-Musica#28]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 뮤지컬에 해시태그 입력 함수 추가

### TODO
1. [ ] Job1 Post 요청으로 해시태그 입력 요청에 대해 DB 저장, 응답 보내기
2. [ ] Job2 Get 요청으로 사이드바의 해시태그를 통해 해당 해시태그와 관련된 뮤지컬 목록 보내주기
3. [ ] Job3 Post 요청으로 해시태그에 동참하기(입력과 동일하게 이미 입력된 해시태그에 유저가 추가됨)

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__2`
- Urgency: `Middle`
