### ISSUE TITLE
배포 환경 구축하기

### ISSUE THREAD

**Issue by ryuseongryong** [codestates/Loca-Musica#3]
### ISSUE
- Group:  `client`, `server`
- Type: `feature`
- Detail: 배포 환경 구축하기(클라이언트, 서버, 데이터베이스)

### TODO
1. [ ] Job1 클라이언트 'Hello World' 띄우기
2. [ ] Job2 서버 'GET' 요청에 따른 응답 보내주기
3. [ ] Job3 데이터베이스 연결 및 구축

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 1.5h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
