### ISSUE TITLE
로그인 페이지 목업 구현

### ISSUE THREAD

**Issue by ryuseongryong** [codestates/Loca-Musica#6]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 로그인 페이지 목업 구현

### TODO
1. [ ] Job1 입력창 만들기
2. [ ] Job2 유효성 검사 메시지 섹션 확보
3. [ ] Job3 회원가입 리다이렉트 버튼
4. [ ] Job4 소셜 로그인 버튼
5. [ ] Job5 모달 구현

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
