### ISSUE TITLE
마이 페이지 목업 구현

### ISSUE THREAD

**Issue by ryuseongryong** [codestates/Loca-Musica#7]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 마이 페이지 목업 구현

### TODO
1. [ ] Job1 각종 정보 표현을 위한 목업 구현
2. [ ] Job2 비밀번호 입력창 구현
3. [ ] Job3 취소 및 확인 버튼 구현
4. [ ] Job4 이미지 업로드 및 출력 구현

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
