### ISSUE TITLE
랜딩페이지 디자인 및 CSS

### ISSUE THREAD

**Issue by ryuseongryong** [codestates/Loca-Musica#8]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 디자인 및 CSS 세부적용

### TODO
1. [ ] Job1 디자인 영역 고민하기
2. [ ] Job2 CSS 세부 적용하기
3. [ ] Job3 로고 여부 고민하기

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `Low`
